name: faculty_marks_app
description: A fully functional Faculty Marks Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  path_provider: ^2.1.1
  path: ^1.8.3
  csv: ^6.0.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  intl: ^0.20.2
  sqflite_common_ffi_web: ^1.0.1+2
  sqflite_common_ffi: ^2.3.0
  file_picker: ^8.1.6
  excel: ^4.0.6
  xml: ^6.5.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
